/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import PromoOpen from "./TJ/Promo/script/PromoOpen"
import ButtonScale from "./TJ/Promo/script/ButtonScale"
import PromoItem from "./TJ/Promo/script/PromoItem"
import P201 from "./TJ/Promo/script/P201"
import P202 from "./TJ/Promo/script/P202"
import P204 from "./TJ/Promo/script/P204"
import P205 from "./TJ/Promo/script/P205"
import P106 from "./TJ/Promo/script/P106"
import GameScene from "./script/Game/GameScene"
import LwgInit from "./script/Frame/LwgInit"
import UIAdsHint from "./script/Game/UIAdsHint"
import UICheckIn from "./script/Game/UICheckIn"
import UIDefeated from "./script/Game/UIDefeated"
import UIDrawCard from "./script/Game/UIDrawCard"
import UILoding from "./script/Game/UILoding"
import UIResurgence from "./script/Game/UIResurgence"
import UISet from "./script/Game/UISet"
import UIShare from "./script/Game/UIShare"
import UISkinTry from "./script/Game/UISkinTry"
import UIStart from "./script/Game/UIStart"
import UIVictory from "./script/Game/UIVictory"
import UIVictoryBox_Cell from "./script/Game/UIVictoryBox_Cell"
import UIVictoryBox from "./script/Game/UIVictoryBox"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("TJ/Promo/script/PromoOpen.ts",PromoOpen);
        reg("TJ/Promo/script/ButtonScale.ts",ButtonScale);
        reg("TJ/Promo/script/PromoItem.ts",PromoItem);
        reg("TJ/Promo/script/P201.ts",P201);
        reg("TJ/Promo/script/P202.ts",P202);
        reg("TJ/Promo/script/P204.ts",P204);
        reg("TJ/Promo/script/P205.ts",P205);
        reg("TJ/Promo/script/P106.ts",P106);
        reg("script/Game/GameScene.ts",GameScene);
        reg("script/Frame/LwgInit.ts",LwgInit);
        reg("script/Game/UIAdsHint.ts",UIAdsHint);
        reg("script/Game/UICheckIn.ts",UICheckIn);
        reg("script/Game/UIDefeated.ts",UIDefeated);
        reg("script/Game/UIDrawCard.ts",UIDrawCard);
        reg("script/Game/UILoding.ts",UILoding);
        reg("script/Game/UIResurgence.ts",UIResurgence);
        reg("script/Game/UISet.ts",UISet);
        reg("script/Game/UIShare.ts",UIShare);
        reg("script/Game/UISkinTry.ts",UISkinTry);
        reg("script/Game/UIStart.ts",UIStart);
        reg("script/Game/UIVictory.ts",UIVictory);
        reg("script/Game/UIVictoryBox_Cell.ts",UIVictoryBox_Cell);
        reg("script/Game/UIVictoryBox.ts",UIVictoryBox);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();