/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameScene from "./script/Game/GameScene"
import LwgInit from "./script/Frame/LwgInit"
import UILoding from "./script/Game/UILoding"
import UIStart from "./script/Game/UIStart"
import UIVictory from "./script/Game/UIVictory"
import GameUI from "./script/GameUI"
import PreGuessCard from "./script/Game/PreGuessCard"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Game/GameScene.ts",GameScene);
        reg("script/Frame/LwgInit.ts",LwgInit);
        reg("script/Game/UILoding.ts",UILoding);
        reg("script/Game/UIStart.ts",UIStart);
        reg("script/Game/UIVictory.ts",UIVictory);
        reg("script/GameUI.ts",GameUI);
        reg("script/Game/PreGuessCard.ts",PreGuessCard);
    }
}
GameConfig.init();