/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LwgInit from "./script/Frame/LwgInit"
import UILoding from "./script/Game/UILoding"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Frame/LwgInit.ts",LwgInit);
        reg("script/Game/UILoding.ts",UILoding);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();